version: '3.8'

services:
  client:
    image: client:latest
    container_name: client
    depends_on:
      - web-api
    build:
      context: client/.
      dockerfile: Dockerfile
    ports:
      - "4000:80"

  web-api:
    container_name: web-api
    image: web-api
    depends_on:
      db:
        condition: service_healthy

    build:
      context: API/
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080 # Change the default port from 80 to 8080
    ports:
      - 8080:8080

  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - dbdata1:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pg_admin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  dbdata1:
