version: '3.8'

services:
  client:
    image: client:latest
    container_name: client_container
    depends_on:
      - "api"
    build:
      context: client/.
      dockerfile: Dockerfile
    ports:
      - "4000:4000"

  api:
    container_name: api_container
    restart: always
    depends_on:
      - "postgres"
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    links:
      - postgres
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=postgres;Username=postgres;Password=postgres"

  postgres:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: contactdb
    ports:
      - 5432:5432
    volumes:
      - dbdata1:/var/lib/postgresql/data

  pgadmin:
    container_name: pg_admin_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
  
  nginx: 
    container_name: loadbalancer_nginx
    build: loadbalancer 
    restart: always
    ports:
      - 80:80 
    links:
      - api
      - client

volumes:
  dbdata1:
