version: '3.8'

services:
  client:
    image: client:latest
    container_name: client_container
    depends_on:
      - "api"
    build:
      context: client/.
      dockerfile: Dockerfile
    ports:
      - "80:80"

  api:
    container_name: api_container
    restart: always
    depends_on:
      - "postgres"
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    links:
      - postgres
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Username=postgres;Password=postgres;Database=postgres"

  postgres:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - dbdata1:/var/lib/postgresql/data

  pgadmin:
    container_name: pg_admin_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

volumes:
  dbdata1:
